"""Email dispatch for sending DA PDFs."""

import logging
import smtplib
from email.message import EmailMessage

from app.config import settings
from app.resilience import CircuitBreaker, CircuitBreakerOpen

logger = logging.getLogger("shipflow.email_dispatch")

_smtp_circuit = CircuitBreaker(
    name="smtp",
    failure_threshold=settings.cb_failure_threshold,
    recovery_timeout=settings.cb_recovery_timeout,
    half_open_max_calls=settings.cb_half_open_max_calls,
)

DA_EMAIL_TEMPLATE = """Dear recipient,

Please find attached the {da_type} Disbursement Account (v{version}) for your review.

DA Reference: {da_id_short}
Status: {status}
Total: {currency} {total}

This document was generated by ShipFlow AI.

Best regards,
{from_name}
"""


async def send_da_email(
    to_addresses: list[str],
    da_data: dict,
    pdf_bytes: bytes,
) -> bool:
    """Send DA email with PDF attachment. Returns True on success."""
    if not settings.smtp_host:
        logger.warning("SMTP not configured; skipping email dispatch")
        return False

    if not to_addresses:
        logger.warning("No recipient addresses; skipping email dispatch")
        return False

    da_id = str(da_data.get("id", ""))
    totals = da_data.get("totals", {})
    currency = da_data.get("currency", "USD")

    body = DA_EMAIL_TEMPLATE.format(
        da_type=da_data.get("type", "Proforma").title(),
        version=da_data.get("version", 1),
        da_id_short=da_id[:8] if da_id else "N/A",
        status=da_data.get("status", "approved").replace("_", " ").title(),
        currency=currency,
        total=f"{totals.get('total', 0):,.2f}",
        from_name=settings.smtp_from_name,
    )

    msg = EmailMessage()
    msg["Subject"] = (
        f"Disbursement Account — {da_data.get('type', 'proforma').title()} (v{da_data.get('version', 1)})"
    )
    msg["From"] = f"{settings.smtp_from_name} <{settings.smtp_from_address}>"
    msg["To"] = ", ".join(to_addresses)
    msg.set_content(body)

    filename = f"DA_{da_id[:8]}_{da_data.get('type', 'proforma')}_v{da_data.get('version', 1)}.pdf"
    msg.add_attachment(
        pdf_bytes,
        maintype="application",
        subtype="pdf",
        filename=filename,
    )

    async def _do_send() -> bool:
        if settings.smtp_use_tls:
            with smtplib.SMTP(
                settings.smtp_host, settings.smtp_port, timeout=settings.smtp_timeout
            ) as server:
                server.starttls()
                if settings.smtp_user:
                    server.login(settings.smtp_user, settings.smtp_password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(
                settings.smtp_host, settings.smtp_port, timeout=settings.smtp_timeout
            ) as server:
                if settings.smtp_user:
                    server.login(settings.smtp_user, settings.smtp_password)
                server.send_message(msg)
        return True

    try:
        result = await _smtp_circuit.call(_do_send)
        logger.info("Email sent for DA %s to %s", da_id[:8], to_addresses)
        return result
    except CircuitBreakerOpen:
        logger.error("SMTP circuit breaker open; skipping email for DA %s", da_id[:8])
        return False
    except Exception:
        logger.exception("Failed to send email for DA %s", da_id[:8])
        return False
