"""PDF generation for Disbursement Accounts using WeasyPrint."""

import logging
from datetime import datetime

logger = logging.getLogger("shipflow.pdf_generator")

DA_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11px; color: #1e293b; margin: 40px; }}
  .header {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; border-bottom: 3px solid #0c4a6e; padding-bottom: 20px; }}
  .company {{ font-size: 20px; font-weight: bold; color: #0c4a6e; }}
  .doc-title {{ font-size: 16px; font-weight: bold; color: #0c4a6e; text-transform: uppercase; margin-bottom: 20px; }}
  .meta-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 25px; }}
  .meta-box {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; }}
  .meta-label {{ font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; margin-bottom: 4px; }}
  .meta-value {{ font-weight: 600; }}
  table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
  thead th {{ background: #0c4a6e; color: #fff; padding: 10px 12px; text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; }}
  tbody td {{ padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }}
  tbody tr:nth-child(even) {{ background: #f8fafc; }}
  .totals {{ margin-top: 10px; text-align: right; }}
  .totals .row {{ display: flex; justify-content: flex-end; gap: 40px; padding: 6px 12px; }}
  .totals .total {{ font-size: 14px; font-weight: bold; color: #0c4a6e; border-top: 2px solid #0c4a6e; padding-top: 8px; }}
  .footer {{ margin-top: 40px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #94a3b8; text-align: center; }}
  .amount {{ text-align: right; }}
  .qty {{ text-align: center; }}
</style>
</head>
<body>
  <div class="header">
    <div class="company">ShipFlow</div>
    <div style="text-align:right">
      <div style="font-size:9px; color:#64748b">Generated</div>
      <div>{generated_date}</div>
    </div>
  </div>

  <div class="doc-title">{da_type} Disbursement Account</div>

  <div class="meta-grid">
    <div class="meta-box">
      <div class="meta-label">DA Reference</div>
      <div class="meta-value">{da_id_short}</div>
    </div>
    <div class="meta-box">
      <div class="meta-label">Version</div>
      <div class="meta-value">v{version}</div>
    </div>
    <div class="meta-box">
      <div class="meta-label">Status</div>
      <div class="meta-value">{status}</div>
    </div>
    <div class="meta-box">
      <div class="meta-label">Currency</div>
      <div class="meta-value">{currency}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:50%">Description</th>
        <th class="qty">Qty</th>
        <th class="amount">Unit Price</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>
    <tbody>
      {line_items_rows}
    </tbody>
  </table>

  <div class="totals">
    <div class="row"><span>Subtotal:</span><span>{currency} {subtotal}</span></div>
    <div class="row"><span>Tax:</span><span>{currency} {tax}</span></div>
    <div class="row total"><span>Total:</span><span>{currency} {total}</span></div>
  </div>

  <div class="footer">
    This document was generated by ShipFlow AI &mdash; {generated_date}
  </div>
</body>
</html>
"""


def render_da_html(da_data: dict) -> str:
    line_items = da_data.get("line_items", [])
    totals = da_data.get("totals", {})
    currency = da_data.get("currency", "USD")

    rows = ""
    for item in line_items:
        rows += (
            f'<tr>'
            f'<td>{item.get("description", "")}</td>'
            f'<td class="qty">{item.get("quantity", 1)}</td>'
            f'<td class="amount">{item.get("unit_price", 0):,.2f}</td>'
            f'<td class="amount">{item.get("amount", 0):,.2f}</td>'
            f'</tr>'
        )

    da_id = str(da_data.get("id", ""))
    return DA_TEMPLATE.format(
        generated_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        da_type=da_data.get("type", "Proforma").title(),
        da_id_short=da_id[:8] if da_id else "N/A",
        version=da_data.get("version", 1),
        status=da_data.get("status", "draft").replace("_", " ").title(),
        currency=currency,
        line_items_rows=rows,
        subtotal=f'{totals.get("subtotal", 0):,.2f}',
        tax=f'{totals.get("tax", 0):,.2f}',
        total=f'{totals.get("total", 0):,.2f}',
    )


async def generate_pdf(da_data: dict) -> bytes:
    """Generate PDF bytes from DA data dict."""
    html = render_da_html(da_data)

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
    except ImportError:
        logger.warning("WeasyPrint not installed; falling back to HTML-as-PDF placeholder")
        pdf_bytes = html.encode("utf-8")

    logger.info("Generated PDF for DA %s (%d bytes)", da_data.get("id", "?"), len(pdf_bytes))
    return pdf_bytes
