apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shipflow
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: shipflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
