apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shipflow

commonLabels:
  app.kubernetes.io/part-of: shipflow
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - worker-deployment.yaml
  - worker-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
  - db-backup-cronjob.yaml
